language-file: "lang-en.yml"

# Update the server list ping MOTD to show when server is scheduled for shutdown/restart
update-ping-motd: true

# Commands to perform just before the server shuts down
shutdown-commands:
  - say Goodbye.

# When should the countdown message be displayed to the user?
# This setting only effects the title, subtitle, and chat.
# Warning: For advanced users only!
display-intervals:
  - timeLeft <= 900 && timeLeft % 300 == 0 # every 5 minutes starting at 15 minutes til
  - timeLeft <= 300 && timeLeft % 60 == 0 # every minute starting at 5 minutes til
  - timeLeft == 30 # 30 seconds til
  - timeLeft <= 10 # every second starting at 10 seconds til

# How many seconds until shutdown should we start showing the actionbar countdown (every second)?
# Set -1 to never show.
display-actionbar: -1

# Should titles be broadcasted alongside the chat messages?
display-title: true

# Automatic restart time
auto-restart:
  enabled: false
  time: "22:00"
  reason: "Nightly Reboot"
  countdown: 900
